### ISSUE TITLE
Расширенный адрес в ЛПУ

### ISSUE THREAD

**Issue by pafik13** [pafik13/doc-merch#3]
Необходимо добавить возможность ввода адреса с геокодированием, то есть:
- подсказка при вводе;
- сохранение GPS координат.

**Comment by dashadasha172** [comment]
в kladr-api GPS координаты не используются, получается отсюда их отдельно брать? https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/About-docpage/

**Comment by dashadasha172** [comment]
нашла где их взять в kladr-api :)

**Comment by pafik13** [comment]
Выполнена в Pull Request "Hospitals page".
